services:
  app:
    build: .
    container_name: snippetbox
    ports:
      - "${APP_PORT}:4000"
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: snippetbox-db
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db_data: